spring:
  application:
    name: Inditex Challenge
  main:
    banner-mode: off
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:inditex
    username: sa
    password: password
    driver-class-name: org.h2.Driver

server:
  error:
    path: /error
    whitelabel:
      enabled: false

logging.level.org:
  springframework.web: DEBUG
  hibernate: ERROR

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuration for the OpenAPI url server
# In case for Production URL can be set with the value "prod-url"
inditex.openapi:
  dev-url: http://localhost:8080